---
abstract: 'Filters for making quoted strings'
author:
  - 'Stephen Clouse <stephenclouse@gmail.com>'
build_requires:
  Test::Class::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mason-Plugin-QuoteFilters
no_index:
  directory:
    - lib/Mason/Plugin/QuoteFilters
requires:
  Mason: 2.00
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Mason-Plugin-QuoteFilters
  repository: git://github.com/StephenClouse/perl-mason-plugin-quotefilters.git
version: 0.001
